name: Docker Image CI
name: 2deviate/pangea-docker
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose --env-file ./config/.env.dev up -d
      - name: Test
        run: docker run --network container:frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost/
