name: pangea-workflow
on: push
jobs:
  test:
    runs-on: alpine:latest
    env:    
      LOGFILENAME : "app.log"
      LOGLEVEL : logging.INFO   
      FLASK_APP: run.py
      FLASK_ENV: 'dev'
      FLASK_PORT: '8000'
      FLASK_HOST: '0.0.0.0'
      FLASK_DEBUG: '1'
      FLASK_APP_TEMPLATE_NAME: 'template.csv'
      FLASK_APP_UPLOAD_FOLDER: 'data/uploads'
      FLASK_APP_DOWNLOAD_FOLDER: 'data/downloads'
      FLASK_FILE_UPLOAD_MAX_LENGTH: 16*1000*1000
      CACHE_REDIS_HOST: 'redis'
      CACHE_REDIS_PORT: 6379
      CACHE_REDIS_PASSWORD: ${{ secrets.CACHE_REDIS_PASSWORD }}
      CACHE_REDIS_DB: 0
      CACHE_REDIS_URL: ''
      CACHE_TYPE: 'RedisCache'
      CACHE_DEFAULT_TIMEOUT: 300
      MYSQL_USER: 'admin'
      MYSQL_DATABASE: 'ffft'
      MYSQL_HOST: 'db'
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      DOCKER_DB_NAME: 'db'
      DOCKER_SERVER_NAME: 'server'
      DOCKER_SERVER_PORT: 8000
      DOCKER_PROXY_NAME: 'proxy'
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      SMTP_USER: 'craig@2deviate.com'
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      SMTP_HOST: 'smtp.gmail.com'
      SMTP_PORT: 465
      EMAIL_FROM_ADDRESS: 'craig@2deviate.com'
      EMAIL_CC_ADDRESSES: 'admin@2deviate.com'
      EMAIL_ATTACHMENT: 'PSTN Sales Planner.xlsx'
      EMAIL_SUBJECT: 'Pangea Exchange Stop Sell Information'
      PROXY_SERVER: 'server:8000'    
    steps:
      - uses: actions/checkout@v2
      - name: Build Stack
        run: docker-compose up -d
      - name: Pangea Health Check
        run: docker run 2deviate/pangea-server:v1.0 curl -s --retry 10 --retry-connrefused http://localhost/api/v1.0/pangea/health
