name: Pangea Proxy Workflow
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      working-directory: /home/src
      run: docker build . --file Dockerfile --tag 2deviate/pangea-proxy:$(date +%s)
