name: Pangea Proxy Build Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 2deviate/pangea-proxy
  
defaults:
  run:
    shell: bash
    working-directory: script
  
jobs:

  generate:
  
    name: Generate Tags
    runs-on: ubuntu-latest
    environment: dev
    
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      
      - name: Get next minor version
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      
      - name: Create new milestone
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          title: ${{ steps.semvers.outputs.patch }}

      - name: Global State
        id: exportmilestone
        run: |
          export TAGVERSION="1.3.28"
          export TITLEVERSION="4.0.0"
          echo "::set-output name=docker_pre_version::${TAGVERSION}"
          echo "::set-output name=docker_title_version::${TITLEVERSION}"
          outputs:
            tag_version: ${{ steps.exportmilestone.outputs.docker_pre_version }}
            title_version: ${{ steps.exportmilestone.outputs.docker_title_version }}

  build:
    
    name: Build Proxy Image
    runs-on: ubuntu-latest
    environment: dev
    
    needs: generate
    
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
    
    - name: Preamble
      id: preamble
      run: |
        echo "${{ needs.generate.outputs.git_pr_sha }}"
        echo "${{ needs.generate.outputs.git_pr_sha_short }}"
    
    - name: Login to Docker Hub Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}      
        
    - name: Login to the Github Package Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}    

    - name: Checkout Repository
      uses: actions/checkout@v3
        
    - name: Setup Docker Image Builder
      uses: docker/setup-buildx-action@v2

    - name: Retrieve Docker Image Metadata
      id: meta
      uses: docker/metadata-action@v3.6.0
      with:
        images: |
          ${{ env.IMAGE_NAME }}:${{ needs.generate.outputs.tag_version }}
          ${{ env.REGISTRY }}/${{ github.repository }}
    
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v2.9.0
      with:
        context: nginx 
        push: true
        tags: ${{  needs.generate.outputs.title_version }}

    - name: Install Cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v1.11.0'
    
    - name: Check Cosign install
      run: cosign version  

    - name: Write signing key to disk
      run: 'echo "$KEY" > cosign.key'
      shell: bash
      env:
        KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}      

    - name: Sign the images      
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        COSIGN_EXPERIMENTAL: 1      
      run: cosign sign --key cosign.key ${{ env.IMAGE_NAME }}:${{  needs.generate.outputs.title_version }}
