name: Pangea Proxy Workflow
on:
  workflow_dispatch:

jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      working-directory: nginx
      run: docker build . --file Dockerfile --tag 2deviate/pangea-proxy:$(date +%s)
